const REACT_START_HOUR: string = window.REACT_START_HOUR || '';
const REACT_NUMBER_OF_HOURS: string = window.REACT_ADDITIONAL_NEXT_DAY_HOURS || '';
const REACT_API_DOMAIN: string = window.REACT_API_DOMAIN || '';
const REACT_VAM_INTERVAL: string = window.REACT_VAM_INTERVAL || '';
const REACT_CAM_INTERVAL: string = window.REACT_CAM_INTERVAL || '';
const REACT_LIVE_SCROLLING_SPEED: string = window.REACT_LIVE_SCROLLING_SPEED || '';

export {
  REACT_START_HOUR,
  REACT_NUMBER_OF_HOURS,
  REACT_API_DOMAIN,
  REACT_VAM_INTERVAL,
  REACT_CAM_INTERVAL,
  REACT_LIVE_SCROLLING_SPEED,
};
